#spring:
#  rabbitmq:
#    host: 192.168.1.129
#    username: fengge
#    password: fengge
#    virtual-host: /fengge

spring:
  rabbitmq:
    host: 192.168.1.129
    username: leyou
    password: leyou
    virtual-host: /leyou